_target_: pytorch_lightning.Trainer

gpus: 0

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

max_epochs: 1
min_epochs: 1

# ckpt path
resume_from_checkpoint: null
