# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "wpf"
  name: ${name}-${turbine_id}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  entity: "lxy764139720"  # set to name of your wandb team
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
